### ISSUE TITLE
Hi, CAn I add my Pattern programs in this repo?

### ISSUE THREAD

**Issue by harshvardhan614** [spandey1296/CODEMONK-2022#66]

**Comment by 002ayush** [comment]
Please assign this issue to me.

**Comment by janvi2021** [comment]
assign me

**Comment by spandey1296** [comment]
Steps to enroll in Hacktoberfest 2022:
1. Register on https://hacktoberfest.com as a participation
2. Fill in all details and synch with the GitHub account
3. Fork the repository: https://github.com/coder2hacker/Explore-open-source.git
4. Send 4 valid PR/MR to the repository and wait to get accepted/merged
